apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: shipping
  template:
    metadata:
      labels:
        tier: shipping
    spec:
      containers:
        - name: shipping
          image: 863518461004.dkr.ecr.us-east-1.amazonaws.com/shipping:latest

