replicaCount: 1
image:
  repository: 975050272810.dkr.ecr.us-east-1.amazonaws.com/shipping
  pullPolicy: Always


serviceAccount:
  create: true
  annotations: {}


securityContext: {}
service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
   limits:
     cpu: 500m
     memory: 1024Mi
   requests:
     cpu: 500m
     memory: 1024Mi
